### ISSUE TITLE
Improve wording in "subsystems/power_supply"

### ISSUE THREAD

**Issue by modelica2015** [modelica2015/ModelicaBook#9] opened 2015-09-21 08:39 UTC
In `text/components/subsystems/power_supply.rst`

Below Simulate FlatCircuit:
 "(because the load connecting the switch to the power supply is open)" --> "(because the switch to the power supply is open)"

**Comment by xogeny** [comment] 2015-09-21 08:50
This is a duplicate of #3.

**Closed by xogeny** 2015-09-21 08:50 UTC

**Comment by dietmarw** [comment] 2015-09-22 09:32
This issue was moved to xogeny/ModelicaBook#266
