### ISSUE TITLE
Typo in quoted Modelica code of comonent_models.rst

### ISSUE THREAD

**Issue by modelica2015** [modelica2015/ModelicaBook#5] opened 2015-09-21 08:26 UTC
`text/source/components/components/component_models.rst`
In Generated Equations and Conservation:
  `ground.flange_a.phi = damper2.flange_b;` --> `ground.flange_a.phi = damper2.flange_b.phi;`
 and
 `damper2.flange_b.phi = spring2.flange_b;` --> `damper2.flange_b.phi = spring2.flange_b.phi;`

**Comment by xogeny** [comment] 2015-09-21 08:51
This is a duplicate of #1.

**Closed by xogeny** 2015-09-21 08:51 UTC
